org: alvintang
app: shoot-message
service: shoot-message
useDotenv: true

provider:
    name: aws
    runtime: nodejs20.x

functions:
    api:
        handler: index.handler
        events:
            - httpApi: "*"
